version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/app.js
      - /public/css/styles.css
    container_name: mail_container
    environment:
      - NODE_ENV=development
